'use client';
import {ChangeEvent,FormEvent,useCallback,useEffect,useState} from 'react';
import QRCode from 'react-qr-code';
import {AdminPager,AdminPageSize} from './AdminPagination';
type Dealer={id:string;dealer_code?:string|null;name:string;owner_name?:string;portal_mobile_number?:string;location?:string;sales_executive?:string;sales_area?:string;sales_territory?:string;state?:string;status:string;referral_token?:string|null;farmer_count:number;redemption_count:number;redeemed_amount:number;outstanding_amount:number;settled_amount:number;is_test:boolean};
type Credit={id:string;note_number:string;dealer_name:string;period_start:string;period_end:string;redemption_count:number;total_amount:number;status:string};
type GeneratedAccount={dealer_code:string;token:string;url:string;dealer:Dealer};
const money=(v:number)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function json<T=Record<string,unknown>>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);const body=await r.json().catch(()=>({})) as Record<string,unknown>;if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:'Request failed');return body as T;}
export default function Dealerships({canManage,canManagePortalMobile,canArchive}:{canManage:boolean;canManagePortalMobile:boolean;canArchive:boolean}){
 const [tab,setTab]=useState<'directory'|'verified'|'credits'>('directory'),[items,setItems]=useState<Dealer[]>([]),[credits,setCredits]=useState<Credit[]>([]),[facets,setFacets]=useState<{states:string[];territories:string[]}>({states:[],territories:[]}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[state,setState]=useState(''),[territory,setTerritory]=useState(''),[account,setAccount]=useState(''),[testData,setTestData]=useState(''),[status,setStatus]=useState('');
 const [page,setPage]=useState(1),[pageSize,setPageSize]=useState<AdminPageSize>(25),[total,setTotal]=useState(0),[selected,setSelected]=useState<Dealer|null>(null),[editor,setEditor]=useState<Partial<Dealer>|null>(null),[accountDealer,setAccountDealer]=useState<Dealer|null>(null),[owner,setOwner]=useState(''),[mobile,setMobile]=useState(''),[qr,setQr]=useState<GeneratedAccount|null>(null),[copied,setCopied]=useState('');
 const [from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({limit:String(pageSize),offset:String(pageSize===0?0:(page-1)*pageSize)});if(search)p.set('search',search);if(state)p.set('state',state);if(territory)p.set('territory',territory);if(status)p.set('status',status);if(testData)p.set('test_data',testData);if(tab==='verified')p.set('account','verified');else if(account)p.set('account',account);const d=await json<{items:Dealer[];total:number;facets:{states:string[];territories:string[]}}>(`/api/admin/portal/dealers?${p}`);setItems(d.items||[]);setTotal(d.total||0);setFacets(d.facets||{states:[],territories:[]});if(tab==='credits'){const c=await json<{items:Credit[]}>('/api/admin/portal/dealer-credit-notes');setCredits(c.items||[]);setTotal(c.items?.length||0);}}catch(e){setError(e instanceof Error?e.message:'Unable to load dealers');}finally{setLoading(false)}},[search,state,territory,status,testData,account,tab,page,pageSize]);
 useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[search,state,territory,status,testData,account,tab,pageSize]);
 async function save(e:FormEvent){e.preventDefault();if(!editor?.name)return;await json(editor.id?`/api/admin/portal/dealers/${editor.id}`:'/api/admin/portal/dealers',{method:editor.id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(editor)});setEditor(null);void load()}
 async function generateAccount(e:FormEvent){e.preventDefault();if(!accountDealer)return;const d=await json<{dealer_code:string;referral_token:string;download_url:string;dealer?:Partial<Dealer>}>(`/api/admin/portal/dealers/${accountDealer.id}/generate-account`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({owner_name:owner,portal_mobile_number:mobile})});setQr({dealer_code:d.dealer_code,token:d.referral_token,url:d.download_url,dealer:{...accountDealer,...d.dealer,owner_name:owner,portal_mobile_number:d.dealer?.portal_mobile_number||mobile,dealer_code:d.dealer_code,referral_token:d.referral_token}});setCopied('');setAccountDealer(null);void load()}
 async function copyText(value:string,label:string){try{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(current=>current===label?'':current),1800)}catch{setError('Clipboard access is unavailable. Select and copy the text manually.')}}
 function dealerMessage(result:GeneratedAccount){const d=result.dealer;return `Hi ${d.owner_name||'Dealer'}, this is your dealer code for the CLSL AI app for ${d.name}: ${result.dealer_code}. Please log in with your registered mobile number ${d.portal_mobile_number||''}. Open CLSL AI: https://ai.croplifescience.com/`;}
 function shareDealerWhatsApp(result:GeneratedAccount){const digits=(result.dealer.portal_mobile_number||'').replace(/\D/g,'');window.open(`https://wa.me/${digits}?text=${encodeURIComponent(dealerMessage(result))}`,'_blank','noopener,noreferrer')}
 async function generateCredit(){if(!selected)return;await json('/api/admin/portal/dealer-credit-notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dealer_id:selected.id,period_start:from,period_end:to})});setTab('credits');setSelected(null);void load()}
 async function settle(note:Credit){const ref=window.prompt('Enter payment or settlement reference');if(!ref)return;await json(`/api/admin/portal/dealer-credit-notes/${note.id}/settle`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settlement_reference:ref})});void load()}
 async function archive(id:string){if(!confirm('Archive this dealer?'))return;await json(`/api/admin/portal/dealers/${id}`,{method:'DELETE'});setSelected(null);void load()}
 async function imported(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const form=new FormData();form.append('file',f);await json('/api/admin/portal/dealers/import',{method:'POST',body:form});e.target.value='';void load()}
 const creditRows=pageSize===0?credits:credits.slice((page-1)*pageSize,page*pageSize);
 return <div className="admin-content dealer-ops">
  <header className="dealer-hero"><div><p className="admin-overline">Partner operations</p><h2>Dealership Network</h2><p>Onboard dealers, track farmer acquisition, reconcile coupon credits and close settlements.</p></div><div className="dealer-header-actions">{canManage&&<label className="admin-secondary">Import CSV<input hidden type="file" accept=".csv" onChange={imported}/></label>}{canManage&&<button className="admin-primary" onClick={()=>setEditor({status:'active'})}>+ Add dealer</button>}</div></header>
  <nav className="dealer-tabs"><button className={tab==='directory'?'active':''} onClick={()=>setTab('directory')}>Dealer directory</button><button className={tab==='verified'?'active':''} onClick={()=>setTab('verified')}>Verified dealers</button><button className={tab==='credits'?'active':''} onClick={()=>setTab('credits')}>Credit notes</button></nav>
  <section className="dealer-kpis"><article><span>Total records</span><b>{total}</b></article><article><span>Accounts in view</span><b>{items.filter(x=>x.dealer_code&&x.owner_name&&x.portal_mobile_number).length}</b></article><article><span>Farmers connected</span><b>{items.reduce((a,x)=>a+Number(x.farmer_count||0),0)}</b></article><article><span>Outstanding credit</span><b>{money(items.reduce((a,x)=>a+Number(x.outstanding_amount||0),0))}</b></article></section>
  {tab!=='credits'&&<section className="dealer-filters"><label className="wide"><span>Search dealer, owner, code or territory</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type to search…"/></label><label><span>State</span><select value={state} onChange={e=>setState(e.target.value)}><option value="">All states</option>{facets.states?.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Territory</span><select value={territory} onChange={e=>setTerritory(e.target.value)}><option value="">All territories</option>{facets.territories?.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Account</span><select value={account} onChange={e=>setAccount(e.target.value)} disabled={tab==='verified'}><option value="">All</option><option value="not_generated">Not generated</option><option value="generated">Generated</option><option value="verified">Dealer + referral ready</option></select></label><label><span>Data</span><select value={testData} onChange={e=>setTestData(e.target.value)}><option value="">Live + test</option><option value="no">Live only</option><option value="yes">Test only</option></select></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></section>}
  {error&&<p className="admin-error">{error}</p>}{loading?<p className="admin-empty">Loading dealer operations…</p>:tab==='credits'?<section className="dealer-table-card"><table className="admin-table"><thead><tr><th>Credit note</th><th>Dealer</th><th>Period</th><th>Coupons</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{creditRows.map(n=><tr key={n.id}><td><b>{n.note_number}</b></td><td>{n.dealer_name}</td><td>{n.period_start} → {n.period_end}</td><td>{n.redemption_count}</td><td><b>{money(n.total_amount)}</b></td><td><span className={`dealer-pill ${n.status}`}>{n.status}</span></td><td><a className="admin-secondary" href={`/api/admin/portal/dealer-credit-notes/${n.id}/download`}>Download</a>{n.status!=='settled'&&canManage&&<button className="admin-primary small" onClick={()=>void settle(n)}>Mark settled</button>}</td></tr>)}</tbody></table><AdminPager page={page} pageSize={pageSize} total={credits.length} shown={creditRows.length} onPage={setPage} onPageSize={setPageSize}/></section>:<section className="dealer-table-card"><table className="admin-table"><thead><tr><th>Dealer</th><th>Account</th><th>State / territory</th><th>Farmers</th><th>Coupons</th><th>Credit</th><th>Actions</th></tr></thead><tbody>{items.map(d=><tr key={d.id}><td><b>{d.name}</b><small>{d.owner_name||'Owner not added'}</small></td><td>{d.dealer_code&&d.owner_name&&d.portal_mobile_number?<><code>{d.dealer_code}</code><small>Referral: {d.referral_token||'not generated'}</small></>:<span className="dealer-pill pending">Not generated</span>}</td><td>{d.state||'—'}<small>{d.sales_territory||'—'}</small></td><td><b>{d.farmer_count||0}</b></td><td>{d.redemption_count||0}<small>{money(d.redeemed_amount)}</small></td><td><b>{money(d.outstanding_amount)}</b><small>Settled {money(d.settled_amount)}</small></td><td><div className="dealer-row-actions"><button onClick={()=>setSelected(d)}>View</button>{canManage&&<button onClick={()=>setEditor(d)}>Edit</button>}{canManage&&!d.referral_token&&<button className="primary" onClick={()=>{setAccountDealer(d);setOwner(d.owner_name||'');setMobile(d.portal_mobile_number||'')}}>Generate account</button>}</div></td></tr>)}</tbody></table><AdminPager page={page} pageSize={pageSize} total={total} shown={items.length} onPage={setPage} onPageSize={setPageSize}/></section>}
  {selected&&<div className="admin-modal" onMouseDown={()=>setSelected(null)}><aside className="dealer-drawer" onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p className="admin-overline">Dealer performance</p><h3>{selected.name}</h3><p>{selected.owner_name||'Owner pending'} · {selected.portal_mobile_number||'Mobile pending'}</p>{selected.dealer_code&&<section className="dealer-login-credential"><span>CLSL AI dealer login code</span><strong>{selected.dealer_code}</strong><button type="button" onClick={()=>void copyText(selected.dealer_code||'','dealer-view-code')}>{copied==='dealer-view-code'?'✓ Copied':'Copy dealer code'}</button></section>}<dl className="dealer-identity-list"><div><dt>City / territory</dt><dd>{selected.location||selected.sales_area||selected.sales_territory||'Not recorded'}</dd></div><div><dt>State</dt><dd>{selected.state||'Not recorded'}</dd></div></dl><div className="drawer-metrics"><article><span>Farmers</span><b>{selected.farmer_count}</b></article><article><span>Coupons</span><b>{selected.redemption_count}</b></article><article><span>Redeemed</span><b>{money(selected.redeemed_amount)}</b></article><article><span>Outstanding</span><b>{money(selected.outstanding_amount)}</b></article></div>{selected.referral_token&&<div className="dealer-qr"><span>Farmer referral QR</span><QRCode value={`https://ai.croplifescience.com/?ref=${selected.referral_token}`} size={150}/><b>{selected.referral_token}</b><small>Farmers may scan this QR or enter the 7-character code manually.</small></div>}<div className="credit-period"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{canManage&&<button className="admin-primary full" onClick={()=>void generateCredit()}>Generate credit note</button>}{canArchive&&<button className="danger-link" onClick={()=>void archive(selected.id)}>Archive dealer</button>}</aside></div>}
  {editor&&<div className="admin-modal"><form className="dealer-modal" onSubmit={save}><h3>{editor.id?'Edit dealer':'Add dealer'}</h3><p>Codes stay hidden until an account is generated with owner name and mobile.</p><label>Dealer name *<input required value={editor.name||''} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><div className="modal-grid"><label>Owner name<input value={editor.owner_name||''} onChange={e=>setEditor({...editor,owner_name:e.target.value})}/></label>{canManagePortalMobile&&<label>Mobile<input value={editor.portal_mobile_number||''} onChange={e=>setEditor({...editor,portal_mobile_number:e.target.value})}/></label>}<label>State<input value={editor.state||''} onChange={e=>setEditor({...editor,state:e.target.value})}/></label><label>Territory<input value={editor.sales_territory||''} onChange={e=>setEditor({...editor,sales_territory:e.target.value})}/></label><label>Status<select value={editor.status||'active'} onChange={e=>setEditor({...editor,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><footer><button type="button" onClick={()=>setEditor(null)}>Cancel</button><button className="admin-primary">Save dealer</button></footer></form></div>}
  {accountDealer&&<div className="admin-modal"><form className="dealer-modal compact" onSubmit={generateAccount}><h3>Generate dealer account</h3><p>{accountDealer.name}</p><label>Owner name *<input required value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Verified mobile number *<input required value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="9876543210"/></label><footer><button type="button" onClick={()=>setAccountDealer(null)}>Cancel</button><button className="admin-primary">Generate both codes</button></footer></form></div>}
  {qr&&<div className="admin-modal"><div className="dealer-modal dealer-account-result"><header><span className="account-success-mark">✓</span><div><p className="admin-overline">Account generated</p><h3>Dealer credentials ready</h3><p>Verify these details before sharing the dealer code.</p></div></header><section className="generated-dealer-code"><span>CLSL AI dealer login code</span><strong>{qr.dealer_code}</strong><div><button className="admin-secondary" type="button" onClick={()=>void copyText(qr.dealer_code,'dealer-code')}>{copied==='dealer-code'?'✓ Copied':'Copy dealer code'}</button><button className="admin-secondary" type="button" onClick={()=>void copyText(dealerMessage(qr),'dealer-message')}>{copied==='dealer-message'?'✓ Message copied':'Copy complete message'}</button></div></section><dl className="generated-dealer-details"><div><dt>Dealership</dt><dd>{qr.dealer.name}</dd></div><div><dt>Owner</dt><dd>{qr.dealer.owner_name||'Not recorded'}</dd></div><div><dt>City / territory</dt><dd>{qr.dealer.location||qr.dealer.sales_area||qr.dealer.sales_territory||'Not recorded'}</dd></div><div><dt>State</dt><dd>{qr.dealer.state||'Not recorded'}</dd></div><div><dt>Registered mobile</dt><dd>{qr.dealer.portal_mobile_number||'Not recorded'}</dd></div></dl><button className="dealer-whatsapp-share" type="button" onClick={()=>shareDealerWhatsApp(qr)}>Share dealer code on WhatsApp</button><section className="generated-referral"><div><p className="admin-overline">For farmer referrals</p><h4>QR and manual code</h4><p>Farmers can scan this QR or enter the code manually. No referral link is shared.</p></div><QRCode value={qr.url} size={132}/><strong>{qr.token}</strong></section><footer><button className="admin-primary" type="button" onClick={()=>setQr(null)}>Done</button></footer></div></div>}
 </div>;
}
