'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import type { InspectionInput, ProviderResult } from '../lib/inspection-ai';
import '../comparison.css';
import '../local-comparison.css';

type Metrics = { crop_match: boolean | null; issue_type_match: boolean | null; issue_match: boolean | null; severity_match: boolean | null; confidence_close: boolean | null; confidence_difference: number | null; overall_agreement_score: number | null; evaluated_weight: number };
type Run = { id: string; inspection_id: string; created_at: string; status: string; context: InspectionInput['context']; providers: string[]; gemini: ProviderResult | null; qwen: ProviderResult | null; metrics: Metrics | null; images?: InspectionInput['images']; input_hash: string; contract_version: string; expert_review: { status: string; crop: string | null; issue: string | null; severity: string | null; notes: string | null } };
type Health = Record<'gemini' | 'qwen', {status: string; model: string; processor?: string; note?: string}>;
const pct = (n: number | null | undefined) => n == null ? '—' : `${Math.round(n * 100)}%`;
const seconds = (n: number | null | undefined) => n == null ? '—' : `${(n / 1000).toFixed(1)}s`;
const mean = (values: number[]) => values.length ? values.reduce((a,b) => a+b,0)/values.length : null;
const label = (value: string) => value.replaceAll('_', ' ');
function outcome(run: Run, provider: 'gemini' | 'qwen') { const r=run[provider]; return r ? r.success ? 'Success' : 'Failed' : run.providers.includes(provider) ? run.status === 'interrupted' ? 'Interrupted' : 'Pending' : 'Not requested'; }

export default function ComparisonDashboard({initialLab = false, localMode = false, configured = true}: {initialLab?: boolean; localMode?: boolean; configured?: boolean}) {
  const [key,setKey]=useState(''); const [token,setToken]=useState(localMode ? 'local-session' : ''); const [runs,setRuns]=useState<Run[]>([]); const [health,setHealth]=useState<Health | null>(null);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [lab,setLab]=useState(initialLab); const [selected,setSelected]=useState<Run | null>(null);
  const [search,setSearch]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [agreement,setAgreement]=useState('all'); const [failure,setFailure]=useState('all'); const [minConfidence,setMinConfidence]=useState(''); const [maxConfidence,setMaxConfidence]=useState('');
  const [files,setFiles]=useState<File[]>([]); const [retain,setRetain]=useState(false); const [context,setContext]=useState<InspectionInput['context']>({crop:'',plant:'',description:'',location:'',notes:'',language:'en'});
  const gallery=useRef<HTMLInputElement>(null); const camera=useRef<HTMLInputElement>(null); const session=useRef(0);
  const api=useCallback(async(action: string, body?: unknown, credential=token) => {
    const query=new URLSearchParams(action);
    const suffix=body?'/lab':query.get('action')==='health'?'/health':query.get('action')==='detail'?'/'+encodeURIComponent(query.get('id')||''):'';
    const endpoint=localMode?`/v1/comparisons${suffix}`:`/api/admin/ai-comparison?${action}`;
    const headers: Record<string,string>=localMode?{'X-CLSL-Local':'1'}:{Authorization:`Bearer ${credential}`};
    if(body)headers['Content-Type']='application/json';
    const response=await fetch(endpoint,{method:body ? 'POST':'GET',headers,body:body ? JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(18000)});
    const text=await response.text(); let data;
    try {data=JSON.parse(text);} catch {throw new Error(`Comparison service returned an invalid response (${response.status}).`);}
    if(!response.ok) throw new Error(typeof data.error==='string' ? data.error : typeof data.detail==='string' ? data.detail : `Request failed (${response.status}).`);
    return data;
  },[token,localMode]);
  useEffect(()=>{if(!localMode)return;let active=true;void api('action=health').then(data=>{if(active)setHealth(data);}).catch(()=>{if(active)setHealth(null);});return()=>{active=false;};},[localMode,api]);
  useEffect(() => {
    if(!token) return; let active=true;
    const refresh=async() => {try {const data=await api('action=list'); if(active) {setRuns(data.items);setError('');}} catch(e) {if(active) setError(e instanceof Error ? e.message:'Unable to refresh.');}};
    void refresh(); const timer=setInterval(refresh,5000); return()=>{active=false;clearInterval(timer);};
  },[token,api]);
  const selectedId=selected?.id;
  useEffect(()=>{if(!token || !selectedId || selected?.status==='complete' || selected?.status==='interrupted') return;let active=true;const refresh=async()=>{try {const data=await api(`action=detail&id=${encodeURIComponent(selectedId)}`);if(active)setSelected(data);}catch(e){if(active)setError(e instanceof Error?e.message:'Cannot load case.');}};void refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer);};},[token,selectedId,selected?.status,api]);
  const unlock=async(e: React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const data=await api('action=list',undefined,key);setRuns(data.items);setToken(key);setKey('');try{setHealth(await api('action=health',undefined,key));}catch{setHealth(null);}}catch(e){setError(e instanceof Error?e.message:'Unable to unlock.');}finally{setBusy(false);}};
  const open=async(id: string)=>{const current=session.current;try{const data=await api(`action=detail&id=${encodeURIComponent(id)}`);if(current===session.current)setSelected(data);}catch(e){if(current===session.current)setError(e instanceof Error?e.message:'Cannot load case.');}};
  const addFiles=(incoming: FileList | null)=>{if(!incoming)return;const next=[...files,...Array.from(incoming)];if(next.length>5 || next.reduce((n,f)=>n+f.size,0)>3*1024*1024 || next.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Choose up to five JPG, PNG or WebP photos, totalling no more than 3 MB.');return;}setFiles(next);setError('');};
  const runLab=async(providers: string[])=>{setBusy(true);setError('');const current=session.current;try{if(!files.length || !retain)throw new Error('Add photos and confirm permission to retain them.');const images=await Promise.all(files.map(file=>new Promise<InspectionInput['images'][number]>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({mimeType:file.type,data:String(reader.result).split(',')[1]});reader.onerror=()=>reject(new Error('Could not read photo.'));reader.readAsDataURL(file);})));const data=await api('action=lab',{input:{context,images},providers,retain_images:retain});if(current===session.current){setLab(false);await open(data.id);}}catch(e){if(current===session.current)setError(e instanceof Error?e.message:'Could not queue comparison.');}finally{setBusy(false);}};
  const filtered=runs.filter(r=>{
    const text=[r.id,r.context.crop,r.context.plant,r.gemini?.diagnosis?.crop,r.qwen?.diagnosis?.crop,r.gemini?.diagnosis?.issue_type,r.qwen?.diagnosis?.issue_type,r.gemini?.diagnosis?.probable_issue,r.qwen?.diagnosis?.probable_issue].join(' ').toLowerCase();
    const score=r.metrics?.overall_agreement_score;const confidence=[r.gemini?.diagnosis?.confidence,r.qwen?.diagnosis?.confidence].filter((v):v is number=>v!=null);
    return text.includes(search.toLowerCase()) && (!from || r.created_at.slice(0,10)>=from) && (!to || r.created_at.slice(0,10)<=to) && (agreement==='all' || agreement==='high' && score!=null && score>=80 || agreement==='medium' && score!=null && score>=50 && score<80 || agreement==='low' && score!=null && score<50 || agreement==='pending' && score==null) && (failure==='all' || failure==='either' && [r.gemini,r.qwen].some(p=>p?.success===false) || failure==='gemini' && r.gemini?.success===false || failure==='qwen' && r.qwen?.success===false || failure==='both_ok' && r.gemini?.success===true && r.qwen?.success===true) && ((!minConfidence && !maxConfidence) || confidence.some(c=>(!minConfidence || c>=Number(minConfidence)/100) && (!maxConfidence || c<=Number(maxConfidence)/100)));
  });
  const paired=filtered.filter(r=>r.metrics);const averageAgreement=mean(paired.map(r=>r.metrics!.overall_agreement_score).filter((n):n is number=>n!=null));
  const matchRate=(field: 'crop_match' | 'issue_match')=>{const values=paired.map(r=>r.metrics![field]).filter(v=>v!=null);return values.length?values.filter(Boolean).length/values.length:null;};
  const days=[...new Set(filtered.map(r=>r.created_at.slice(0,10)))].sort().slice(-7);
  return <main className="comparison-app">
    <header className="cmp-header"><Link href={localMode ? "https://ai-crop-dun.vercel.app/" : "/"} className="cmp-brand">CLSL <span>Crop Life AI</span></Link><span className="cmp-badge">INTERNAL EVALUATION</span>{token && !localMode && <button onClick={()=>{session.current++;setToken('');setRuns([]);setSelected(null);setHealth(null);setFiles([]);setError('');}}>Lock dashboard</button>}</header>
    <div className="cmp-intro"><p className="cmp-eyebrow">{localMode ? "LOCAL LAB · NO PASSWORD NEEDED" : "AI COMPARISON"}</p><h1>Compare Gemini and Qwen</h1><p>{localMode ? "Images and comparison history are stored on this laptop. Gemini uses its API; Qwen runs through your local Ollama." : "Use the local lab on the laptop where Qwen is installed. Your main farmer app continues to use Gemini."} Agreement is not diagnostic accuracy.</p></div>
    {error && <div className="cmp-alert" role="alert">{error}</div>}
    {!configured && !localMode ? <section className="cmp-panel cmp-login"><h2>No administrator key needed for local testing</h2><p>Open the lab on the laptop where Ollama is installed. Upload crop photos there to compare Gemini and Qwen privately.</p><p><a className="cmp-local-link" href="http://127.0.0.1:8001/" target="_blank" rel="noopener noreferrer">Open local comparison lab →</a></p><small>If the lab does not open, start it from the project folder with <code>npm run comparison:start</code>. After restarting the laptop, run that command again. This link does not connect a phone or another computer to your laptop.</small><p className="cmp-setup-note">The public website is not connected to the local dataset. Shared online comparison will need a private server connection; no public access to your images has been enabled.</p></section> : !token ? <form className="cmp-panel cmp-login" onSubmit={unlock}><h2>Administrator access</h2><p>Use the dedicated comparison admin key. It stays in this tab’s memory and is cleared when you lock or reload.</p><label>Admin key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required minLength={32}/></label><button className="cmp-primary" disabled={busy}>{busy?'Connecting…':'Open private dashboard'}</button><small>The private comparison service must be configured. Your farmer application continues to work independently.</small></form> : <>
      <nav className="cmp-tabs" aria-label="Evaluation views"><button aria-pressed={!lab} onClick={()=>setLab(false)}>Comparison dashboard</button><button aria-pressed={lab} onClick={()=>setLab(true)}>Image test lab</button></nav>
      <section className="cmp-health cmp-panel"><div><strong>Provider health</strong><p>Configuration and reachability, not a diagnostic test.</p></div>{(['gemini','qwen'] as const).map(p=><div key={p}><b>{p==='gemini'?'Gemini':'Local Qwen'}</b><span>{health ? `${label(health[p].status)} · ${health[p].model}`:'Not checked'}</span>{health?.[p].processor && <small>{health[p].processor}</small>}</div>)}<button onClick={async()=>{try{setHealth(await api('action=health'));}catch(e){setError(e instanceof Error?e.message:'Health unavailable.');}}}>Refresh health</button></section>
      {lab ? <section className="cmp-panel cmp-lab"><div><p className="cmp-eyebrow">CONTROLLED TEST</p><h2>Give both models the same evidence</h2><p>Upload once. The original images and context go to both providers. Jobs run one at a time to protect the CPU.</p><input hidden ref={gallery} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{addFiles(e.target.files);e.target.value='';}}/><input hidden ref={camera} type="file" accept="image/*" capture="environment" onChange={e=>{addFiles(e.target.files);e.target.value='';}}/><div className="cmp-actions"><button onClick={()=>camera.current?.click()}>Take crop photo</button><button onClick={()=>gallery.current?.click()}>Upload photos</button></div><p>1–5 photos · JPG, PNG or WebP · 3 MB total</p><ul>{files.map((f,i)=><li key={`${f.name}-${i}`}>{f.name} <button aria-label={`Remove ${f.name}`} onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>Remove</button></li>)}</ul></div><div className="cmp-form-grid">{(['crop','plant','location','description','notes'] as const).map(field=><label key={field}>{field==='description'?'Visible symptoms':label(field)}<input value={context[field]} maxLength={field==='description'||field==='notes'?800:field==='location'?120:80} onChange={e=>setContext({...context,[field]:e.target.value})}/></label>)}<label>Output language<select value={context.language} onChange={e=>setContext({...context,language:e.target.value})}>{[['en','English'],['hi','Hindi'],['gu','Gujarati'],['mr','Marathi'],['bn','Bengali'],['bho','Bhojpuri']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label></div><label className="cmp-check"><input type="checkbox" checked={retain} onChange={e=>setRetain(e.target.checked)}/> I have permission to use and retain these images in the private evaluation dataset.</label><div className="cmp-actions">{[['gemini'],['qwen'],['gemini','qwen']].map(providers=><button key={providers.join()} className={providers.length===2?'cmp-primary':''} disabled={busy || !retain || !files.length} onClick={()=>runLab(providers)}>{busy?'Submitting…':providers.length===2?'Run both models':`Run ${providers[0]==='gemini'?'Gemini':'Qwen'}`}</button>)}</div><small>Qwen has a configurable 180-second timeout. A timeout or offline model is recorded as a failure, never a diagnosis. No catalogue products or doses are generated in this lab.</small></section> : <>
      <section className="cmp-filters cmp-panel"><label>Crop, issue, category or ID<input placeholder="Search comparisons" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>From (UTC)<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To (UTC)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Agreement<select value={agreement} onChange={e=>setAgreement(e.target.value)}><option value="all">All scores</option><option value="high">80–100 points</option><option value="medium">50–79 points</option><option value="low">Below 50 points</option><option value="pending">Not scored</option></select></label><label>Provider failure<select value={failure} onChange={e=>setFailure(e.target.value)}><option value="all">All results</option><option value="either">Either provider failed</option><option value="gemini">Gemini failed</option><option value="qwen">Qwen failed</option><option value="both_ok">Both successful</option></select></label><label>Min confidence, either (%)<input type="number" min="0" max="100" value={minConfidence} onChange={e=>setMinConfidence(e.target.value)}/></label><label>Max confidence, same provider (%)<input type="number" min="0" max="100" value={maxConfidence} onChange={e=>setMaxConfidence(e.target.value)}/></label></section>
      <section className="cmp-stats">{[['Cases in view',filtered.length],['Scored pairs',paired.length],['Gemini successful',filtered.filter(r=>r.gemini?.success).length],['Qwen successful',filtered.filter(r=>r.qwen?.success).length],['Mean agreement',averageAgreement==null?'—':`${averageAgreement.toFixed(0)}/100`],['Crop match',pct(matchRate('crop_match'))],['Issue match',pct(matchRate('issue_match'))],['Provider failures',filtered.reduce((n,r)=>n+Number(r.gemini?.success===false)+Number(r.qwen?.success===false),0)]].map(([title,value])=><div className="cmp-panel" key={title}><span>{title}</span><strong>{value}</strong></div>)}</section>
      <section className="cmp-chart-grid">{(['gemini','qwen'] as const).map(p=><div className="cmp-panel" key={p}><h2>{p==='gemini'?'Gemini':'Qwen'} latency</h2><p>Mean successful response: <b>{seconds(mean(filtered.filter(r=>r[p]?.success).map(r=>r[p]!.latencyMs)))}</b></p><p>Failure rate: <b>{pct((()=>{const finished=filtered.filter(r=>r[p]);return finished.length?finished.filter(r=>r[p]?.success===false).length/finished.length:null;})())}</b> · completed attempts only</p><div className="cmp-bars">{days.map(day=>{const value=mean(filtered.filter(r=>r.created_at.startsWith(day)&&r[p]?.success).map(r=>r[p]!.latencyMs));return <div key={day}><span>{day.slice(5)}</span><meter aria-label={`${day} average ${p} latency`} min={0} max={p==='qwen'?180000:45000} value={value||0}/><b>{seconds(value)}</b></div>;})}{!days.length&&<p>No measurements yet.</p>}</div></div>)}<div className="cmp-panel"><h2>Agreement over time</h2><p>Last seven recorded days · fixed 100-point scale</p><div className="cmp-bars">{days.map(day=>{const value=mean(paired.filter(r=>r.created_at.startsWith(day)).map(r=>r.metrics!.overall_agreement_score).filter((v):v is number=>v!=null));return <div key={day}><span>{day.slice(5)}</span><meter aria-label={`${day} mean agreement`} min={0} max={100} value={value||0}/><b>{value==null?'—':value.toFixed(0)}</b></div>;})}</div></div></section>
      <section className="cmp-panel"><h2>Comparison records</h2><p>{filtered.length} records · refreshes every 5 seconds · most recent first</p><div className="cmp-table-wrap"><table><thead><tr>{['Date / case','Crop input / Gemini / Qwen','Gemini issue','Qwen issue','Confidence G / Q','Time G / Q','Status G / Q','Agreement','Details'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}<small>{r.id.slice(0,8)} · {r.status}</small></td><td>{r.context.crop||'Not supplied'}<small>Gemini: {r.gemini?.diagnosis?.crop||'Unknown'}</small><small>Qwen: {r.qwen?.diagnosis?.crop||'Unknown'}</small></td><td>{r.gemini?.diagnosis?.probable_issue||'—'}<small>{label(r.gemini?.diagnosis?.issue_type||'')}</small></td><td>{r.qwen?.diagnosis?.probable_issue||'—'}<small>{label(r.qwen?.diagnosis?.issue_type||'')}</small></td><td>{pct(r.gemini?.diagnosis?.confidence)} / {pct(r.qwen?.diagnosis?.confidence)}</td><td>{seconds(r.gemini?.latencyMs)} / {seconds(r.qwen?.latencyMs)}</td><td>{outcome(r,'gemini')} / {outcome(r,'qwen')}</td><td>{r.metrics?.overall_agreement_score==null?'—':`${r.metrics.overall_agreement_score}/100`}<small>{r.metrics ? `${r.metrics.evaluated_weight}% evaluated`:''}</small></td><td><button onClick={()=>open(r.id)}>View case</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="cmp-empty"><h3>No comparisons in this view</h3><p>Run a controlled test in the image lab, or enable shadow mode after connecting the private service.</p><button onClick={()=>setLab(true)}>Open image lab</button></div>}</section>
      </>}
      {selected && <section className="cmp-panel cmp-detail" aria-label="Selected comparison"><div className="cmp-detail-head"><div><p className="cmp-eyebrow">CASE DETAILS · {selected.status}</p><h2>{selected.context.crop||'Crop inspection'}</h2><small>{selected.inspection_id} · {new Date(selected.created_at).toLocaleString()}</small></div><button onClick={()=>setSelected(null)}>Close case</button></div><p>{selected.context.description || 'No symptom notes supplied.'} {selected.context.location && `Location: ${selected.context.location}.`}</p><div className="cmp-photos">{selected.images?.map((image,i)=><img key={i} src={`data:${image.mimeType};base64,${image.data}`} alt={`Uploaded crop evidence ${i+1}`}/>)}</div><details><summary>Exact submitted context and input fingerprint</summary><pre>{JSON.stringify({context:selected.context,input_hash:selected.input_hash,contract:selected.contract_version},null,2)}</pre></details><div className="cmp-matches">{selected.metrics ? Object.entries(selected.metrics).map(([field,value])=><span className={value===false?'cmp-diff':''} key={field}>{label(field)}: <b>{value===null?'Not evaluated':typeof value==='boolean'?value?'Match':'Different':typeof value==='number'?Number(value.toFixed(3)):String(value)}</b></span>):<p>Agreement is calculated only after both providers return valid diagnoses.</p>}</div><div className="cmp-provider-grid">{(['gemini','qwen'] as const).map(p=><ProviderCard key={p} title={p==='gemini'?'Gemini · production provider':'Qwen · evaluation only'} result={selected[p]} state={outcome(selected,p)}/>)}</div><div className="cmp-review"><h3>Expert review: {label(selected.expert_review.status)}</h3><p>No expert-verified labels have been entered. Model agreement does not establish correctness or authorize treatment.</p><dl>{Object.entries(selected.expert_review).filter(([key])=>key!=='status').map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></div></section>}
      <footer className="cmp-footer">Score: crop 25 + issue category 20 + issue name 35 + severity 10 + confidence within 10 percentage points 10. Unknown fields earn no points; evaluated coverage is shown separately. Text matching uses normalization and limited crop aliases, not clinical validation. Diagnosis-only models cannot write to the CLSL product catalogue.</footer>
    </>}
  </main>;
}

function ProviderCard({title,result,state}: {title:string;result:ProviderResult|null;state:string}) {
  return <article className="cmp-provider"><h3>{title}</h3><p><b>{state}</b>{result && ` · ${result.model} · ${seconds(result.latencyMs)}`}</p>{result?.error&&<div className="cmp-alert">{result.error}</div>}{result?.diagnosis&&<><dl>{Object.entries(result.diagnosis).map(([field,value])=><div key={field}><dt>{label(field)}</dt><dd>{Array.isArray(value)?value.length?<ul>{value.map((v,i)=><li key={i}>{v}</li>)}</ul>:'None reported':value==null?'Not provided':typeof value==='boolean'?value?'Yes':'No':field.includes('confidence')?pct(value as number):label(String(value))}</dd></div>)}</dl><details><summary>Final response JSON (no thinking trace)</summary><pre>{JSON.stringify(result.rawResponse,null,2)}</pre></details></>}{!result&&<p>The job runs in the private service. You can leave this page and return later.</p>}</article>;
}
