'use client';
import { useRef, useState } from 'react';

type View = 'home'|'inspect'|'assistant'|'products'|'history';
const products = [
  {name:'CLS Safeguard',type:'Insecticide',ingredient:'Approved active ingredient',target:'Sucking pests',crops:'Cotton · Chilli',tone:'gold'},
  {name:'CLS Protect',type:'Fungicide',ingredient:'Approved active ingredient',target:'Fungal diseases',crops:'Tomato · Potato',tone:'blue'},
  {name:'CLS Growth+',type:'Crop Nutrition',ingredient:'Balanced micronutrients',target:'Nutrient support',crops:'Multiple crops',tone:'green'},
];

export default function Home(){
 const inputRef=useRef<HTMLInputElement>(null); const [files,setFiles]=useState<File[]>([]); const [view,setView]=useState<View>('home'); const [analysed,setAnalysed]=useState(false); const [chat,setChat]=useState(''); const [messages,setMessages]=useState<string[]>([]);
 const nav=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:'smooth'})};
 const send=()=>{if(!chat.trim())return;setMessages([...messages,chat.trim()]);setChat('')};
 return <main className="app-shell">
  <header className="topbar"><button className="brand plain" onClick={()=>nav('home')}><span className="brand-mark">CL</span><span><strong>Crop Life</strong><small>AI Farmer Assistant</small></span></button><nav className="topnav" aria-label="Main navigation"><button className={view==='inspect'?'active':''} onClick={()=>nav('inspect')}>AI Inspection</button><button className={view==='assistant'?'active':''} onClick={()=>nav('assistant')}>AI Assistant</button><button className={view==='products'?'active':''} onClick={()=>nav('products')}>Products</button><button className={view==='history'?'active':''} onClick={()=>nav('history')}>My Inspections</button></nav><button className="profile-button" aria-label="Open farmer profile">RK</button></header>
  {view==='home'&&<HomeView nav={nav}/>} 
  {view==='inspect'&&<section className="workspace"><PageTitle eyebrow="AI Crop Doctor" title="Inspect your crop" text="Add clear photos from different angles. The more context you share, the more useful the probable assessment can be."/><div className="inspection-layout"><div className="inspect-card large"><InspectionForm inputRef={inputRef} files={files} setFiles={setFiles} onAnalyse={()=>setAnalysed(true)}/></div><Tips/></div>{analysed&&<Result onClose={()=>setAnalysed(false)} nav={nav}/>}</section>}
  {view==='assistant'&&<section className="workspace"><PageTitle eyebrow="Farmer Assistant" title="Ask in your own words" text="Get practical help with crops, visible symptoms, cultivation and approved Crop Life products."/><div className="chat-shell"><div className="chat-head"><span className="assistant-orb">✦</span><div><b>Crop Life AI</b><small>Ready to help · English</small></div></div><div className="chat-body"><div className="ai-message">Namaste! Tell me which crop you grow or upload a crop photo. How can I help today?</div>{messages.map((m,i)=><div key={i} className="user-message">{m}</div>)}{messages.length>0&&<div className="ai-message">I can help assess that. For a crop-specific answer, please share the crop name, growth stage, location and a clear photo if symptoms are visible.</div>}<div className="suggestions"><button onClick={()=>setChat('My cotton leaves are curling')}>Cotton leaves are curling</button><button onClick={()=>setChat('Help me find a product')}>Find a product</button><button onClick={()=>setChat('How much spray water per acre?')}>Spray calculation</button></div></div><div className="chat-input"><button aria-label="Attach image">＋</button><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about your crop..."/><button className="send" onClick={send}>↑</button></div></div></section>}
  {view==='products'&&<section className="workspace"><PageTitle eyebrow="Approved portfolio" title="Find a Crop Life solution" text="Browse company-managed product information. Final claims, dosage and usage must always follow the approved label."/><div className="searchbar"><span>⌕</span><input placeholder="Search by crop, pest, disease or product"/><button>Search</button></div><div className="filter-row"><button className="selected">All products</button><button>Insecticides</button><button>Fungicides</button><button>Crop nutrition</button></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.name}><div className={`product-art ${p.tone}`}><span>CLS</span><b>{p.name.split(' ')[1]||'Crop'}</b></div><small>{p.type}</small><h2>{p.name}</h2><dl><div><dt>For</dt><dd>{p.target}</dd></div><div><dt>Crops</dt><dd>{p.crops}</dd></div><div><dt>Composition</dt><dd>{p.ingredient}</dd></div></dl><button>View approved details →</button></article>)}</div><p className="demo-disclaimer">Demonstration product records only. Replace these with Crop Life Science’s verified catalog before production use.</p></section>}
  {view==='history'&&<section className="workspace"><PageTitle eyebrow="My records" title="Inspection history" text="Return to previous inspections, review assessments and continue the conversation."/><div className="history-list"><History date="27 Aug 2026" crop="Cotton" issue="Possible whitefly activity" confidence="87%"/><History date="20 Aug 2026" crop="Cotton" issue="No visible issue detected" confidence="82%"/><History date="11 Aug 2026" crop="Tomato" issue="Possible nutrient stress" confidence="71%"/></div></section>}
  <footer><span>Crop Life Science Limited</span><p>Responsible crop care, supported by intelligence.</p><button onClick={()=>nav('home')}>Home ↑</button></footer>
 </main>
}

function HomeView({nav}:{nav:(v:View)=>void}){return <><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span/> Your crop companion</p><h1>Understand your crop.<br/><em>Act with confidence.</em></h1><p>Upload clear photos and describe what you see. Crop Life AI helps identify possible issues and connects you with approved crop solutions.</p><div className="trust-row"><span>✓ Probable assessment</span><span>✓ Approved products only</span><span>✓ Inspection history</span></div></div><div className="home-panel"><span className="leaf-shape">⌁</span><small>AI-assisted crop care</small><h2>See something unusual?</h2><p>Start a guided inspection in under a minute.</p><button onClick={()=>nav('inspect')}>Inspect my crop <span>→</span></button><div className="panel-stats"><span><b>3</b> simple steps</span><span><b>5</b> photos supported</span></div></div></section><section className="quick-section"><div className="section-label"><span>Start here</span><p>Everything you need for a healthier crop</p></div><div className="quick-grid"><Quick featured icon="⌁" label="Most used" title="AI Crop Inspection" text="Upload crop photos and understand visible symptoms." onClick={()=>nav('inspect')}/><Quick icon="✦" label="Ask anything" title="Farmer Assistant" text="Get practical answers about crops and products." onClick={()=>nav('assistant')}/><Quick icon="◫" label="Approved range" title="Find a Product" text="Search Crop Life solutions by crop or problem." onClick={()=>nav('products')}/></div></section><section className="assistant-strip"><div><span className="assistant-orb">✦</span><div><p>Crop Life AI Assistant</p><h2>What would you like to know about your crop?</h2></div></div><button onClick={()=>nav('assistant')}>Ask the assistant <span>→</span></button></section></>}
function Quick(p:{featured?:boolean;icon:string;label:string;title:string;text:string;onClick:()=>void}){return <button onClick={p.onClick} className={`quick-card ${p.featured?'featured':''}`}><span className="quick-icon">{p.icon}</span><div><small>{p.label}</small><h3>{p.title}</h3><p>{p.text}</p></div><b>→</b></button>}
function PageTitle(p:{eyebrow:string;title:string;text:string}){return <div className="page-title"><p className="eyebrow"><span/>{p.eyebrow}</p><h1>{p.title}</h1><p>{p.text}</p></div>}
function InspectionForm({inputRef,files,setFiles,onAnalyse}:{inputRef:React.RefObject<HTMLInputElement|null>;files:File[];setFiles:(f:File[])=>void;onAnalyse:()=>void}){return <><div className="card-heading"><span className="step-badge">01</span><div><h2>Add crop photos</h2><p>Up to 5 images · JPG, PNG or HEIC</p></div></div><button className={`upload-zone ${files.length?'has-files':''}`} onClick={()=>inputRef.current?.click()}><input ref={inputRef} hidden type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/><span className="upload-icon">↑</span><strong>{files.length?`${files.length} photo${files.length>1?'s':''} ready`:'Upload crop photos'}</strong><small>{files.length?files.map(f=>f.name).join(' · '):'Take a photo or choose from your device'}</small></button><div className="form-row"><label><span>Crop <small>optional</small></span><select defaultValue=""><option value="">Select your crop</option><option>Cotton</option><option>Tomato</option><option>Chilli</option><option>Wheat</option><option>Rice</option></select></label><label><span>Location <small>optional</small></span><input placeholder="e.g. Ahmedabad, Gujarat"/></label></div><label className="full-field"><span>What do you notice? <small>optional</small></span><textarea placeholder="Describe colour changes, spots, insects or when the problem started..."/></label><button className="primary-button" disabled={!files.length} onClick={onAnalyse}>Analyse my crop <span>→</span></button><p className="safety-note">AI results are probable assessments, not guaranteed diagnoses. Always follow the approved label and local expert advice.</p></>}
function Tips(){return <aside className="tips"><h3>Photos that help</h3><ol><li><b>Whole plant</b><span>Show the plant and its surroundings</span></li><li><b>Affected area</b><span>Take a clear close-up of symptoms</span></li><li><b>Leaf underside</b><span>Capture insects or growth underneath</span></li></ol><div className="privacy-box"><b>Your crop data</b><p>Inspection images should only be reused for model improvement with clear consent.</p></div></aside>}
function Result({onClose,nav}:{onClose:()=>void;nav:(v:View)=>void}){return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="result-modal"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow"><span/> Probable assessment</p><div className="result-head"><div><small>Crop identified</small><h2>Cotton</h2></div><span className="confidence"><b>87%</b> confidence</span></div><div className="issue-box"><small>POSSIBLE ISSUE · PEST</small><h3>Whitefly activity</h3><p>Visible leaf curling and yellowing may be consistent with sucking-pest activity. Inspect the underside of leaves to confirm visible insects.</p></div><div className="symptoms"><b>Observed signs</b><span>Leaf curling</span><span>Yellowing</span><span>Visible stress</span></div><div className="result-actions"><button onClick={()=>nav('products')}>View matching products</button><button className="secondary" onClick={()=>nav('assistant')}>Ask a follow-up</button></div><p className="demo-disclaimer">Illustrative result for the Phase 1 prototype. A production AI provider is not connected yet.</p></div></div>}
function History(p:{date:string;crop:string;issue:string;confidence:string}){return <article className="history-item"><div className="history-date">{p.date}</div><span className="crop-avatar">⌁</span><div><small>{p.crop}</small><h3>{p.issue}</h3></div><span className="history-confidence">{p.confidence}</span><button>Open →</button></article>}
