ALTER TABLE dealers ADD COLUMN IF NOT EXISTS sales_executive VARCHAR(180);
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS sales_area VARCHAR(100);
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS sales_region VARCHAR(100);
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS sales_territory VARCHAR(100);
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS state VARCHAR(100);
